name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: actions-checkout
        uses: actions/checkout@v4

      - id: setup-bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-dependencies
        run: bun install

      - id: run-tests
        run: bun run test
